# GitLab CI/CD pipeline configuration file

stages:
  - lint
  - test

lint_job:
  stage: lint
  script:
    - echo "Проверка README на наличие ссылок на изображения"
    - grep -E "!\[.*\]\(img/.*\.png\)" README.md || echo "Изображения не найдены"

test_job:
  stage: test
  script:
    - echo "Тесты будут здесь"
